language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "nightly"
  - "pypy3"
script:
  - python -m unittest discover -v tests/ 'test_*.py'
jobs:
  include:
    - stage: code check
      name: flake8
      python: 3.6
      install: pip install -q flake8
      script: flake8 .
    - stage: code check
      name: isort
      python: 3.6
      install: pip install -q isort
      script: isort --check-only --recursive .
